<?php

namespace Mav\ExoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function QueryAllArticle()
    {
        $dql = "SELECT a FROM MavExoBundle:Article a";
        $query = $this->getEntityManager()->createQuery($dql);
        
        return $query;
    }
}
