<?php

namespace Mav\ExoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BreveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreveRepository extends EntityRepository
{
    public function QueryAllArticle()
    {
        $dql = "SELECT b FROM MavExoBundle:Breve b";
        $query = $this->getEntityManager()->createQuery($dql);
        
        return $query;
    }
}
