<?php

namespace Mav\ExoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BreveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreveRepository extends EntityRepository
{
}
