<?php

namespace Mav\ExoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findOneRandom()
    {
        $em = $this->getEntityManager();
        $max = $em->createQuery('
            SELECT MAX(c.id) FROM MavExoBundle:Category c
            ')
            ->getSingleScalarResult();
        return $em->createQuery('
            SELECT c FROM MavExoBundle:Category c
            WHERE c.id >= :rand
            ')
            ->setParameter('rand', rand(0,$max))
            ->setMaxResults(1)
            ->getSingleResult();
    }
}
